Make dockerfile prod work

diff --git a/bin/docker-entrypoint b/bin/docker-entrypoint
--- a/bin/docker-entrypoint
+++ b/bin/docker-entrypoint
@@ -12,7 +12,8 @@ fi
 
 # If running the rails server then create or migrate existing database
 if [ "${1}" == "./bin/rails" ] && [ "${2}" == "server" ]; then
-  ./bin/rails db:prepare
+  ./bin/rails db:create || echo "Database already exists or creation failed - continuing..."
+  ./bin/rails db:migrate
 fi
 
 exec "${@}"
